/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckboxIndexRouteImport } from './routes/checkbox/index'
import { Route as ButtonIndexRouteImport } from './routes/button/index'
import { Route as ButtonGroupIndexRouteImport } from './routes/button-group/index'
import { Route as AutocompleteIndexRouteImport } from './routes/autocomplete/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckboxIndexRoute = CheckboxIndexRouteImport.update({
  id: '/checkbox/',
  path: '/checkbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonIndexRoute = ButtonIndexRouteImport.update({
  id: '/button/',
  path: '/button/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonGroupIndexRoute = ButtonGroupIndexRouteImport.update({
  id: '/button-group/',
  path: '/button-group/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutocompleteIndexRoute = AutocompleteIndexRouteImport.update({
  id: '/autocomplete/',
  path: '/autocomplete/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autocomplete': typeof AutocompleteIndexRoute
  '/button-group': typeof ButtonGroupIndexRoute
  '/button': typeof ButtonIndexRoute
  '/checkbox': typeof CheckboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autocomplete': typeof AutocompleteIndexRoute
  '/button-group': typeof ButtonGroupIndexRoute
  '/button': typeof ButtonIndexRoute
  '/checkbox': typeof CheckboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autocomplete/': typeof AutocompleteIndexRoute
  '/button-group/': typeof ButtonGroupIndexRoute
  '/button/': typeof ButtonIndexRoute
  '/checkbox/': typeof CheckboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/autocomplete' | '/button-group' | '/button' | '/checkbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/autocomplete' | '/button-group' | '/button' | '/checkbox'
  id:
    | '__root__'
    | '/'
    | '/autocomplete/'
    | '/button-group/'
    | '/button/'
    | '/checkbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutocompleteIndexRoute: typeof AutocompleteIndexRoute
  ButtonGroupIndexRoute: typeof ButtonGroupIndexRoute
  ButtonIndexRoute: typeof ButtonIndexRoute
  CheckboxIndexRoute: typeof CheckboxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkbox/': {
      id: '/checkbox/'
      path: '/checkbox'
      fullPath: '/checkbox'
      preLoaderRoute: typeof CheckboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button/': {
      id: '/button/'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button-group/': {
      id: '/button-group/'
      path: '/button-group'
      fullPath: '/button-group'
      preLoaderRoute: typeof ButtonGroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autocomplete/': {
      id: '/autocomplete/'
      path: '/autocomplete'
      fullPath: '/autocomplete'
      preLoaderRoute: typeof AutocompleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutocompleteIndexRoute: AutocompleteIndexRoute,
  ButtonGroupIndexRoute: ButtonGroupIndexRoute,
  ButtonIndexRoute: ButtonIndexRoute,
  CheckboxIndexRoute: CheckboxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
